name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      # Step 5: Build the Project (if needed)
      - name: Build Project
        working-directory: ./frontend
        run: npm run build

      # Step 6: Decode and Set Up Firebase Credentials
      - name: Decode Service Account JSON
        run: |
          mkdir -p $HOME/firebase
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > $HOME/firebase/service-account.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase/service-account.json

      # Step 7: Authenticate Google Cloud
      - name: Authenticate with Google Cloud
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase/service-account.json"
          gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
         
